### ISSUE TITLE
Nuxt components inside Storyblok Rich-Text editor

### ISSUE THREAD

**Issue by cetchells** [SebbeJohansson/sebbejohansson-front#22]
I saw your post here: [nuxt static](https://github.com/nuxt/framework/discussions/515), really helpful.
I had a look at nuxt3 and storyblok just wondering if you got components in richtext editor to resolve in nuxt3.
Suggestions below don't seem to work
[https://www.storyblok.com/tp/nuxt-components-inside-rich-text](https://www.storyblok.com/tp/nuxt-components-inside-rich-text)

**Comment by SebbeJohansson** [comment]
Hi @cetchells. Am i understanding it correctly that you are wondering about adding blocks using this feature?
![image](https://user-images.githubusercontent.com/5083273/193042258-ef427bcf-7212-40f9-8de0-9956c2d40a01.png)
![image](https://user-images.githubusercontent.com/5083273/193042225-7d4b39f6-a56f-46de-a5a9-5c7c5bea8229.png)

I have not tested that. I can take a look during next week if you want?

**Comment by cetchells** [comment]
Yeh exactly that. 
There is a related issue in storyblok/nuxt repo:
[https://github.com/storyblok/storyblok-nuxt/issues/172#issuecomment-1209010052](https://github.com/storyblok/storyblok-nuxt/issues/172#issuecomment-1209010052)
Would be great if that worked because I'm trying to migrate a wordpress site that has wp shortcodes embedded in the content.
I want to try and transform those into storyblok components.

**Comment by SebbeJohansson** [comment]
Hm okay interesting. Since i am using `useStoryblokApi().richTextResolver.render(props.blok.text))` and not https://github.com/m4rvr/storyblok-rich-text-renderer (since it cant handle ssr with pretender correctly) or similar to render I would have to do it myself.

Here you can see that it completely removes the blok node:
![image](https://user-images.githubusercontent.com/5083273/193134495-3d0c359d-faa1-4ffe-9179-0024f6000962.png)

I didn't have much time to look at this today, but I have a work in progress version:
```vue
<script setup lang="ts">
import { Richtext } from 'storyblok-js-client';

const props = defineProps({ blok: Object });
const nuxtApp = useNuxtApp();
const textObject = { ...props.blok.text };
const nodes = [];
Object.entries(textObject.content).forEach(([key, node]) => {
  if (node.type === 'blok') {
    const blok = {
      content: node.attrs?.body?.[0],
    };
    nodes.push({
      key,
      type: 'blok',
      content: {
        blok,
      },
    });
  } else {
    nodes.push({
      key,
      type: 'html',
      content: nuxtApp.$formatRichText(useStoryblokApi().richTextResolver.render({
        type: 'doc',
        content: [
          node,
        ],
      } as Richtext)),
    });
  }
});
</script>

<template>
  <div v-editable="blok" class="text">
    <div v-for="node in nodes" :key="node.key">
      <component
        :is="$resolveStoryBlokComponent(node.content.blok)"
        v-if="node.type === 'blok'"
        :blok="node.content.blok.content"
      />
      <div v-else v-html="node.content" />
    </div>
  </div>
</template>

<style>
.text img {
  max-width: 100%;
}
</style>
```

What I do:
I loop through all the nodes in the richtext. For each node I add it to an array representing the finished content. For the nodes that is a blok, I add it to the array with the type "blok" and for the rest (that I assume is proper richtext nodes that the resolver can handle) I add to the array with type "HTML" and I also resolve the richText right away.
This means that I get an array of each "node" that I want to render in the correct order.

The finished code does this:
![image](https://user-images.githubusercontent.com/5083273/193142275-34262262-4f0a-498d-adeb-d8cf91a7649f.png)
![image](https://user-images.githubusercontent.com/5083273/193142281-97f8344a-21e5-4def-a58d-71ae117f5db1.png)

Let me know if any of this was confusing. I will most likely refactor this when I have more time and add it to my finished code in production.

**Comment by SebbeJohansson** [comment]
I made a blogpost about this: https://sebbejohansson.com/blog/storyblok-richtext-in-line-block-support-for-nuxt3-with-ssr-and-prerender
